window.GLOSSARY = [
  ["PLC", "Programmable Logic Controller: a rugged industrial computer that reads inputs, runs a program in a repeating cycle and drives outputs."],
  ["TIA Portal", "Totally Integrated Automation Portal: Siemens' engineering software for PLCs, HMIs and drives."],
  ["STEP 7", "The PLC programming part of TIA Portal."],
  ["WinCC", "The HMI (operator screen) part of TIA Portal."],
  ["PLCSIM", "Siemens' simulator that runs a virtual S7-1200/1500 on your PC."],
  ["SIMATIC", "Siemens' family name for its automation products."],
  ["CPU", "The processing module that stores and runs the program."],
  ["Scan cycle", "One pass of: write outputs, read inputs, run the program, housekeeping. Repeats continuously."],
  ["Process image (PII / PIQ)", "A snapshot copy of inputs (PII) and outputs (PIQ) in CPU memory. The program works with the image, not the live hardware."],
  ["Input / Output", "Signals into or out of the PLC. Digital = on/off. Analog = continuous value."],
  ["Digital signal", "A two-state signal: 0 or 1, FALSE or TRUE."],
  ["Analog signal", "A continuous signal such as 4-20 mA or 0-10 V representing a measured quantity."],
  ["Normally open (NO)", "A contact that is open at rest and closes when actuated. In ladder, passes power when its bit is 1."],
  ["Normally closed (NC)", "A contact closed at rest and opens when actuated. In ladder, passes power when its bit is 0."],
  ["Rung / Network", "One horizontal line of a ladder diagram. TIA Portal calls it a network."],
  ["Contact", "A ladder element that tests a bit and passes power if the condition is met."],
  ["Coil", "A ladder element at the end of a rung that writes a bit. A normal coil follows the rung."],
  ["Set / Reset coil", "Coils that latch a bit on (Set) or off (Reset) and keep it until the opposite coil acts."],
  ["Seal-in (latching)", "A contact of the output in parallel with the start button so the output holds itself on."],
  ["Edge (P / N)", "A one-scan pulse when a signal rises (P, positive) or falls (N, negative)."],
  ["TON / TOF / TP", "On-delay, off-delay and pulse timers."],
  ["PT / ET", "Preset time and elapsed time of a timer."],
  ["CTU / CTD / CTUD", "Count up, count down, and up/down counters."],
  ["LAD", "Ladder Diagram: graphical PLC language resembling relay wiring."],
  ["FBD", "Function Block Diagram: graphical language of logic boxes."],
  ["SCL", "Structured Control Language: Siemens' Structured Text, a Pascal-like text language."],
  ["IEC 61131-3", "The international standard defining PLC programming languages."],
  ["OB", "Organization Block: an entry point called by the CPU's operating system (OB1 main cycle, OB100 startup...)."],
  ["FC", "Function: a reusable block without memory."],
  ["FB", "Function Block: a reusable block with memory held in an instance data block."],
  ["DB", "Data Block: a block that stores data. Global DBs are shared; instance DBs belong to an FB call."],
  ["Instance DB", "The data block holding one FB call's static memory."],
  ["Multi-instance", "A block (e.g. a timer) declared inside an FB's Static section so it uses the FB's own instance DB."],
  ["UDT / PLC data type", "A user-defined structure grouping related variables into one reusable type."],
  ["Tag", "A symbolic name linked to an address, e.g. Start_PB for %I0.0."],
  ["Absolute address", "The hardware location of a signal such as %I0.0, %Q0.3, %MW10, %IW64."],
  ["Optimized access", "Block mode where TIA Portal chooses memory layout and you use names rather than offsets."],
  ["Retentive", "Memory that keeps its value through power-off or STOP to RUN."],
  ["Hysteresis", "Two different thresholds for switching on and off, so a signal near the limit does not chatter."],
  ["NORM_X / SCALE_X", "Instructions that normalise a value to 0.0-1.0 and scale it to engineering units."],
  ["27648", "The full-scale raw value of a Siemens analog input in its nominal range."],
  ["State machine", "A design where a state variable says what phase the machine is in, with explicit transitions."],
  ["Download / Upload", "Download sends the project to the CPU. Upload reads it back."],
  ["Online / Offline", "Offline: the project on your PC. Online: connected to a running CPU."],
  ["Force", "Overriding a signal permanently, ignoring the program. Dangerous on real equipment."],
  ["PROFINET", "The Ethernet-based industrial network used by Siemens for programming, I/O and drives."],
  ["HMI", "Human-Machine Interface: an operator screen showing the machine and accepting commands."],
  ["HMI runtime", "The software on a panel or PC that shows the screens and talks to the PLC."],
  ["Integrated connection", "An HMI-to-PLC link inside one TIA project, so the HMI can pick PLC tags directly."],
  ["Acknowledge (alarm)", "An operator's confirmation that an alarm has been seen."],
  ["Recipe", "A named set of process values for one product, loaded into the machine as a unit."],
  ["IO controller / IO device", "In PROFINET, the controller (the PLC) drives I/O provided by IO devices (stations, drives)."],
  ["Subnet mask", "A number that says which part of an IP address is the network and which is the device."],
  ["Modbus TCP", "A simple register-based protocol common on third-party instruments."],
  ["OPC UA", "A vendor-neutral, secure protocol that publishes typed, named data to IT systems."],
  ["STW1 / ZSW1", "The PROFIdrive control word (commands to the drive) and status word (replies from it)."],
  ["PID", "Proportional-integral-derivative control: a feedback method that holds a process value at a setpoint."],
  ["PID_Compact", "The PID instruction and technology object for S7-1200/1500 with built-in tuning."],
  ["Overshoot / offset", "Overshoot: the value goes past the setpoint. Offset: it settles short of it."],
  ["Technology object (TO)", "A configured object such as an axis or PID controller with its own editor and instruction blocks."],
  ["PackML", "A standard state model (idle, execute, hold, stop, abort...) used to make machines behave consistently."],
  ["Library type", "A versioned block or UDT stored in a library and updated centrally in all projects that use it."],
  ["Diagnostic buffer", "The CPU's time-stamped event log. First place to look when something fails."],
  ["Safe Torque Off (STO)", "A drive safety function that removes torque safely."],
  ["PL / SIL", "Performance Level and Safety Integrity Level: measures of how reliable a safety function must be."],
  ["Defense in depth", "Layering several independent security measures so one failure is not fatal."],
  ["DMZ", "A buffer network between IT and the control network that holds gateways."],
  ["IEC 62443", "The standard family for industrial automation and control system security."],
  ["FAT / SAT", "Factory Acceptance Test (at the builder) and Site Acceptance Test (at the customer)."],
    ["S7-1200 G2", "The newer generation of the S7-1200 with faster CPUs, more memory and a smaller housing. Needs a recent TIA Portal (V20 with HSP, or V21)."],
  ["HSP", "Hardware Support Package: an add-on that adds newer devices to an installed TIA Portal version."],
  ["S7-PLCSIM Advanced", "A separately licensed simulator for S7-1500 with extra features such as multiple instances and scripting. The classic S7-PLCSIM covers S7-1200 and S7-1500."],
  ["SIMATIC AX", "Siemens' text-first engineering tool built on Visual Studio Code, aimed at Git-based, software-style PLC development."],
  ["SCE", "Siemens Automation Cooperates with Education: free TIA Portal learning documents for education."],
  ["XIC / XIO", "Allen-Bradley names for the normally open (examine if closed) and normally closed (examine if open) contacts."],
  ["OTE / OTL / OTU", "Allen-Bradley output energize (coil), latch and unlatch (Set and Reset)."],
  ["KOP / FUP / AWL", "German names for LAD, FBD and STL that appear in Siemens documents."],
  ["Flip-flop", "A circuit that stores one bit and changes it on a clock edge."],
  ["Register / shift register", "A group of flip-flops holding a value. A shift register moves its bits one place per clock."],
  ["Ripple counter", "A counter built from toggling flip-flops where each stage halves the frequency of the previous one."],
  ["Ring / Johnson counter", "Shift-register counters used for sequencing: a ring circulates one 1; a Johnson feeds back the inverted last bit."],
  ["Encoder (quadrature)", "A position sensor producing two pulse trains A and B a quarter period apart so direction can be detected."],
  ["Servo", "A motor with feedback and a controller closing position, speed and current loops."],
  ["Electronic gear / cam", "Software coupling of axes: a gear follows a master at a ratio; a cam follows a position table."],
  ["Dead time (theta)", "The delay before a process starts to react to a change in its input."],
  ["Time constant (tau)", "How slowly a first-order process moves toward its final value."],
  ["Ultimate gain Ku", "The loop gain at which a feedback loop oscillates steadily. Used by Ziegler-Nichols tuning."],
  ["SIMC / CHR / Ziegler-Nichols", "Three families of rules for choosing PID parameters from a process model or an oscillation test."],
  ["Invert control logic", "A PID_Compact option that makes the controller reverse acting, needed when raising the output lowers the process value."],
  ["SCADA", "Supervisory Control And Data Acquisition: collecting, displaying, archiving and supervising data from many PLCs and sites."],
  ["RTU", "Remote terminal unit: a small controller at a remote site that reports to SCADA."],
  ["Historian", "A database that archives process values and alarms with time stamps."],
  ["P2000", "The SINAMICS reference speed: the speed that corresponds to 100 % (16384) in the PROFIdrive speed words."],
  ["Loop check", "Verifying every I/O signal from the field device to its PLC tag."],  ["ET 200SP", "Siemens distributed I/O system placed near the machine, connected by PROFINET."],
  ["Contactor", "A heavy-duty relay that switches a motor or other power load. Its coil is driven by a small control signal such as a PLC output."],
  ["Overload relay", "A thermal device that opens a contact when motor current stays too high, protecting the motor."],
  ["MPCB", "Motor protection circuit breaker: a breaker with adjustable thermal and magnetic trip set to the motor's rated current."],
  ["Galvanic isolation", "Separation of two circuits so no direct electrical connection exists between them, for example a relay coil and its contacts."],
  ["Flyback diode", "A diode across a DC coil that absorbs the voltage spike when the coil is switched off."],
  ["Direct-on-line (DOL)", "The simplest motor starter: the motor is connected straight to full line voltage through a contactor."],
  ["Star-delta", "A reduced-voltage starting method: windings start in star (about one third of the current), then switch to delta."],
  ["Soft starter", "A device that ramps the voltage to a motor for a gentle start and stop; it cannot control running speed."],
  ["VFD", "Variable frequency drive: converts the supply to a variable frequency and voltage to control motor speed."],
  ["PNP / NPN", "Sensor output types. PNP switches +24 V to the signal wire (sourcing); NPN switches it to 0 V (sinking)."],
  ["Live zero", "The 4 mA start of a 4 to 20 mA signal, so that 0 mA can be recognised as a wire break."],
  ["Pt100", "A platinum resistance temperature sensor with 100 ohm at 0 degrees C."],
  ["Thermocouple", "A temperature sensor made of two dissimilar metals that produces a small voltage depending on temperature."],
  ["Encoder", "A sensor that reports rotation or position, as pulses (incremental) or as a value (absolute)."],
  ["5/2 valve", "A pneumatic directional valve with five ports and two positions, typically driving a double-acting cylinder."],
  ["Fail position", "The position (open, closed or last) a valve or output takes when its signal or power is lost."],
  ["P&ID", "Piping and instrumentation diagram: the map of a process plant showing equipment, lines and instruments."],
  ["I/O list", "The table that maps every field signal to a terminal, PLC address and tag name."],
  ["Force table", "A TIA Portal table that fixes physical inputs or outputs to a value regardless of the program. Dangerous if left active."],
  ["Array", "A numbered row of items of the same data type, accessed by an index."],
  ["Struct", "A group of related values of different data types treated as one variable."],
  ["VARIANT", "A pointer to a variable of any type, used to write generic blocks."],
  ["Slice access", "Addressing a bit, byte or word within a larger variable, such as .%X3 for bit 3."],
  ["Heartbeat", "A counter or bit that a sender changes regularly so a receiver can detect that the link is alive."],
  ["GRAFCET / SFC", "A sequence description with steps and transitions. IEC 60848 and IEC 61131-3 (Sequential Function Chart)."],
  ["Cyclic interrupt", "An OB that runs at a fixed time interval regardless of the main cycle."],
  ["Hardware interrupt", "An OB that runs immediately when a configured input event occurs."],
  ["HSC", "High-speed counter: dedicated hardware that counts fast pulses independent of the scan."],
  ["Trace", "A TIA Portal tool that records tag values inside the CPU at cycle resolution for later analysis."],
  ["AOI", "Add-On Instruction: the Allen-Bradley equivalent of a function block."],
  ["MQTT", "A lightweight publish/subscribe messaging protocol widely used for IoT and cloud connection."],
  ["OEE", "Overall equipment effectiveness: availability times performance times quality."],
  ["ISA-95", "The model for integrating enterprise and control systems, with its levels from field to ERP."],
  ["F-CPU", "A fail-safe CPU that runs a standard program and a separate signed safety program."],
  ["PROFIsafe", "A safety protocol on top of PROFINET that detects corrupted, delayed, repeated or missing messages."],
  ["Passivation", "Replacing the value of a failed F-I/O channel with a fail-safe value; the system keeps running safely."],
  ["Reintegration", "Switching a passivated F-I/O channel back to process data after the fault is removed and acknowledged."],
  ["STO", "Safe Torque Off: a drive safety function that removes the torque without mechanical contactors."],
  ["Collective signature", "A value that identifies the exact contents of a safety program; it changes with any modification."],
  ["Discrepancy time", "The maximum time two redundant channels may disagree before a fault is raised."],
  ["Startdrive", "The TIA Portal option for commissioning SINAMICS drives."],
  ["PROFIdrive telegram", "The standardised set of control and status words exchanged cyclically between PLC and drive."],
  ["Simatic SD", "A text-based export format of TIA Portal V21 that makes Git version control practical."],
  ["PLCSIM Advanced", "A separate Siemens simulator for S7-1500 CPUs with an API, virtual Ethernet adapter and multiple instances."],
  ["Test Suite", "TIA Portal option for automated testing of blocks."],
  ["LMQTT", "Siemens library with a function block that lets an S7 CPU act as an MQTT client."],
  ["Unit test", "A test that exercises one block in isolation with defined inputs and expected outputs."]
];
